name: Docker Image CI

on:
  workflow_dispatch: {}
  workflow_call:
    inputs:
      image-name:
        type: string
        required: true


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Load environment variables from docker.env
      run: |
        cat docker.env >> $GITHUB_ENV
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/debian_vnc
        tags: |
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          type=sha,prefix=,suffix=,format=short
          type=ref,event=tag
    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and (conditionally) push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          TMM_URL=${{ env.TMM_URL }}
          MEO_DICT_URL=${{ env.MEO_DICT_URL }}
          WIKI_DICT_URL=${{ env.WIKI_DICT_URL }}
          PAN_115_URL=${{ env.PAN_115_URL }}
          PAN_BAIDU_URL=${{ env.PAN_BAIDU_URL }}
